Feat: Allow users to input their own fetch functions (for proxies)
buape/utilities pull request #64
Opened 2023-07-04 23:09 UTC by OIRNOIR

You can pass a function that works similarly to the node-fetch fetch function which will be used instead of the node-fetch function.

2023-07-04 23:12 UTC, OIRNOIR commented
AI is bad

2023-07-05 01:06 UTC, thewilloftheshadow requested changes
Can you add a changeset please

2023-07-05 01:25 UTC, thewilloftheshadow approved these changes

2023-07-05 02:03 UTC, thewilloftheshadow approved these changes

2023-07-05 02:03 UTC, OIRNOIR commented
@thewilloftheshadow It wants you to approve my commit before merging

2023-07-05 14:48 UTC, merged